spring:
  application:
    name: bocaditos-llc
  datasource:
    url: ${BOCADITOS_DB_URL:jdbc:mysql://localhost:3306/bocaditos_llc}
    username: ${BOCADITOS_DB_USERNAME:root}
    password: ${BOCADITOS_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  thymeleaf:
    cache: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
